### ISSUE TITLE
I can't build this

### ISSUE THREAD

**Issue by MCTyler** [TechzoneMC/TechUtils#4]
Do you have this Jar available somewhere? I can't get the project to build and I'm trying to revive hunger games.
[06:35:19 WARN]: [LibsHungergames] Task #6 for LibsHungergames v${project.version} generated an exception
java.lang.NoClassDefFoundError: Could not initialize class me.libraryaddict.Hungergames.techcable.ActionBar$SpigotActionBarHandler
    at me.libraryaddict.Hungergames.techcable.ActionBar.getActionBarHandler(ActionBar.java:66) ~[?:?]
    at me.libraryaddict.Hungergames.techcable.ActionBar.isSupported(ActionBar.java:60) ~[?:?]
    at me.libraryaddict.Hungergames.Hungergames.onSecond(Hungergames.java:317) ~[?:?]
    at me.libraryaddict.Hungergames.Hungergames.access$200(Hungergames.java:45) ~[?:?]
    at me.libraryaddict.Hungergames.Hungergames$4.run(Hungergames.java:277) ~[?:?]
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-76236cb-62a2169]
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-76236cb-62a2169]
    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot.jar:git-Spigot-76236cb-62a2169]
    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-76236cb-62a2169]
    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-76236cb-62a2169]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-76236cb-62a2169]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51

**Comment by Techcable** [comment]
That class is included in libs hungergames.
Are you sure you are using LibsHungeragames@796ec8195b9a4255dd5a757f014812f669de35e8?

**Comment by MCTyler** [comment]
That Link is a 404 error. I used the one you gave to a guy VIA DropBox and I built my own from Libs source. Both have same error. I used this one...https://github.com/libraryaddict/LibsHungergames

**Comment by Techcable** [comment]
Whoops I mean libraryaddict/LibsHungergames@796ec81

**Comment by MCTyler** [comment]
I rewrote it and got rid of action bar and fixed the player.length error...Thx.
